# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='oss',
            field=models.CharField(default=1, max_length=256, verbose_name='oss\u7684\u5730\u5740'),
            preserve_default=False,
        ),
    ]
