# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_pixabay'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
