# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_pixabay_row'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pixabay_Row',
        ),
    ]
